# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w05a
yarn_mappings=25w05a+build.4
loader_version=0.16.10

# Mod Properties
mod_version=1.0.2-25w05a
maven_group=com.coolerpromc.moregears
archives_base_name=moregears

# Dependencies
fabric_version=0.115.2+1.21.5
energy_api_version=4.1.0
jei_version=19.21.0.247
rei_version=18.0.796