# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.2

# Mod Properties
mod_version=2.0.4+1.21.11-fabric
maven_group=com.coolerpromc.moregears
archives_base_name=moregears

# Dependencies
fabric_version=0.139.4+1.21.11
energy_api_version=4.2.0
jei_version=27.0.0.1
rei_version=19.0.805