# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w21a
yarn_mappings=25w21a+build.1
loader_version=0.16.14

# Mod Properties
mod_version=2.0.0-25w21a-fabric
maven_group=com.coolerpromc.moregears
archives_base_name=moregears

# Dependencies
fabric_version=0.124.3+1.21.6
energy_api_version=4.2.0
jei_version=19.21.0.247
rei_version=19.0.805